apiVersion: v1
kind: Service
metadata:
  labels:
    app: external-svc
  name: external-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-svc
subsets:
- addresses:
  - ip: 35.200.45.101
  - ip: 34.85.7.193
  - ip: 34.84.88.51
  ports:
  - port: 80
