apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-nodeport
  name: nodejs-nodeport
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    app: nodejs
  type: NodePort
