apiVersion: v1
kind: Pod
metadata:
  name: nginx-manual
  labels:
    app: nginx
#  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
