apiVersion: v1
kind: Pod
metadata:
  name: nodejs-manual-v2
  labels:
    createion_method: manual
    env: pod
spec:
  containers:
  - name: nodejs
    image: gasbugs/nodejs
    ports:
    - containerPort: 8080
      protocol: TCP
