apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      containers:
      - image: luksa/batch-job
        name: batch-job
      restartPolicy: OnFailure
