apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubia
  name: kubia
spec:
  containers:
  - image: luksa/kubia-unhealthy
    name: kubia
    livenessProbe:
      httpGet:
        path: /
        port: 8080
