apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubia-svc-lb
  name: kubia-svc-lb
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30002
  selector:
    app: kubia
  type: LoadBalancer
