apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: ssd-monitor
  name: ssd-monitor
spec:
  selector:
    matchLabels:
      app: ssd-monitor
  template:
    metadata:
      labels:
        app: ssd-monitor
    spec:
      nodeSelector:
        disk: ssd
      containers:
      - image: luksa/ssd-monitor
        name: ssd-monitor
