apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: jenkins-namespace 
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  namespace: jenkins-namespace
spec:
  containers:
  - name: jenkins
    image: jenkins
    ports:
    - containerPort: 8080
      protocol: TCP

