apiVersion: v1
kind: Pod
metadata:
  labels:
    app: two-containers
  name: two-containers
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - image: nginx
    name: nginx-container
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
      readOnly: true
  - image: debian
    name: debian-container
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the debian container >> /pod-data/index.html"]
