apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs-rc
spec:
  replicas: 3
  selector:
    app: nodejs
  template:
    metadata:
      name: nodejs
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: gasbugs/nodejs
        ports:
        - containerPort: 8080
          protocol: TCP
