apiVersion: v1
data:
  DB_Password: UGFzc3cwcmQhMA==
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_Password
    ports:
    - containerPort: 3306
      protocol: TCP
