# node-env.yaml

apiVersion: v1
data:
  password: YWRtaW4xMjM0IQ==
  username: YWRtaW4=
kind: Secret
metadata:
  name: db-user-pass
  namespace: default
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: envar-secret
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: DEMO_GREETING
      #value: "Hello from the environment"
      valueFrom:
        secretKeyRef:
          name: db-user-pass
          key: username
    - name: DEMO_FAREWELL
      #value: "Such a sweet sorrow"
      valueFrom:
        secretKeyRef:
          name: db-user-pass
          key: password
