#apiVersion: networking.k8s.io/v1beta1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodejs-ingress
spec:
  rules:
  - host: www.gasbugs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nodejs-np
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-np
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-rs
  labels:
    app: nodejs
    #tier: frontend
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - nodejs
  template:
    metadata:
      name: nodejs
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: gasbugs/nodejs
        ports:
        - containerPort: 80
          protocol: TCP
