apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80          # Service's Port
      targetPort: 8080  # Pod's Port
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-rs
  labels:
    app: nodejs
    tier: frontend
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - nodejs
  template:
    metadata:
      name: nodejs
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: gasbugs/nodejs
        ports:
        - containerPort: 80
          protocol: TCP
