apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nodejs
  name: nodejs
spec:
  imagePullSecrets:
  - name: rolroralra-registry
  containers:
  - image: registry.rolroralra.com/nodejs
    name: nodejs
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
  dnsPolicy: ClusterFirst
  restartPolicy: Always
