apiVersion: v1
kind: Namespace
metadata:
  name: blue
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: blue
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 80          # Service's Port
      targetPort: 8080  # Pod's Port
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
  namespace: blue
  labels:
    app: jenkins
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - jenkins
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
