apiVersion: v1
kind: Pod
metadata:
  name: downward-api-env
  labels:
    ksy: "1111"
spec:
  containers:
  - image: busybox
    name: main
    command: ["sleep"]
    args: ["9999999"]
    env:
    #- name: POD_LABEL
    #  valueFrom:
    #    fieldRef:
    #      fieldPath: metatdata.labels
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name 
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
    - name: CONTAINER_CPU_REQUEST_MILICORES
      valueFrom:
        resourceFieldRef:
          #continaerName: main
          resource: requests.cpu
          divisor: 1m
    - name: CONTAINER_MEMORY_LIMIT_KIBIBYTES
      valueFrom:
        resourceFieldRef:
          #continaerName: main
          resource: limits.memory
          divisor: 1Ki
    resources:
      requests:
        cpu: 15m
        memory: 100Ki 
      limits:
        cpu: 100m
        memory: 4Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
