apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  labels:
    app: alpine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine:3.4
        command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
        #ports:
        #- containerPort: 8080
        #  protocol: TCP
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: alpine
#spec:
#  selector:
#    app: alpine
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8080
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: myapp-pod
#  labels:
#    app: myapp
#spec:
#  containers:
#  - name: myapp-container
#    image: busybox
#    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
