apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ssd-jenkins-rs
  labels:
    app: ssd-jenkins
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ssd-jenkins
  template:
    metadata:
      #name: jenkins
      labels:
        app: ssd-jenkins
    spec:
      nodeSelector:
        ssd: "true"
      containers:
      - name: ssd-jenkins
        image: jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        resources:
          requests:
            cpu: "1m"
            memory: "200Mi"
          limits:
            cpu: "2m"
            memory: "400Mi"
