#apiVersion: v1
#kind: Pod
#metadata:
#  name: nginx
#  labels:
#    app: nginx
#spec:
#  containers:
#  - image: nginx
#    name: nginx
#    resources:
#      requests:
#        cpu: "1m"
#        memory: "200Mi"
#    ports:
#    - containerPort: 80
#      protocol: TCP
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      #name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "1m"
            memory: "200Mi"
          limits:
            cpu: "2m"
            memory: "400Mi"
