apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
  - image: mongo
    name: test-container
    volumeMounts:
    - mountPath: /data/db
      name: mongodb
  volumes:
  - name: mongodb
    # This GCE PD must already exist.
    gcePersistentDisk:
      pdName: mongodb # GCE Persistent Storage Name
      fsType: ext4
