apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodejs-ingress
  labels:
    app: nodejs-ingress
spec:
  rules:
  - host: kubia.example.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: nodejs
          servicePort: 80
