apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-deploy
  name: nodejs-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
        enabled: "false"
    spec:
      containers:
      - image: rolroralra/nodejs
        name: nodejs
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
