apiVersion: v1
kind: Pod
metadata:
  name: fortune
  namespace: default
  labels:
    app: nginx-fortune
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    gitRepo:
      repository: https://github.com/luksa/kubia-website-example.git
      revision: master
      directory: .
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fortune-np-svc
  name: fortune-np-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30001
    protocol: TCP
  selector:
    app: nginx-fortune
